language: node_js
node_js:
  - "0.12.7"
env:
  - NODE_ENV=travis
services:
  - redis-server
  - mongodb
before_script:
  - npm install -g memdb/memdb
  - memdbcluster stop -c ./test/memdb.conf.js
  - memdbcluster drop -c ./test/memdb.conf.js
